t=input("enter your brithdate ")
e=input("enter your brithdate ")
l=input("enter your brithdate ")
r=input("enter your brithdate ")
k=input("enter your brithdate ")
print(t)
print(e)
print(l)
print(r)
print(k)